name: "General checks: Lints, Tests, Docs"

on:
  workflow_call:

jobs:
  # check python formatting
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/ruff-action@v3
        name: Ruff

  # run tests on both mac and ubuntu, across all python versions
  # additionally run type checker here as it's part of the tests
  test:
    runs-on: ${{ matrix.os }}
    env:
      UV_NO_EDITABLE: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install the project
        run: uv sync --dev --verbose
      - name: Run tests
        run: uv run pytest -v
      - name: Run basedpyright
        run: uv run basedpyright
